dist: xenial
language: python
python:
    - "3.7"

install:
    - pip install -r requirements.txt

before_script:
    - find /usr/local/share -name "py4j*.jar"
    - find /usr/share -name "py4j*.jar"

script:
    pytest
