dist: xenial
language: python
python:
    - "3.7"

install:
    - pip install -r requirements.txt

before_script:
    - export RES=$(find /usr/local/share -name "py4j*.jar")
    - echo "FILE: ${RES}"

script:
    pytest
